#./django-docker/docker-compose.yml
version: '3.7'

services:
  web:
    build:
         context: ./app 
         dockerfile: Dockerfile
    command: python manage.py runserver
    volumes:
      - ./app/:/opt/app/
    ports:
      - 8080:8000
    env_file:
      - ./env/django.env